# Generated by Django 4.2.3 on 2023-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_is_draft_alter_topic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
