# Generated by Django 4.2.3 on 2023-08-13 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ('courses', '0005_alter_course_discount_price_alter_course_price'),
        ("courses", "0006_alter_assignment_options_alter_course_options_and_more"),
    ]

    operations = []
