# Generated by Django 4.2.3 on 2023-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by_enrollments', to='courses.lesson'),
        ),
    ]
