# Generated by Django 4.2.3 on 2023-08-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_media_options_alter_media_user'),
        ('quizzes', '0002_alter_quiz_options_quiz_created_at_quiz_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('TF', 'True/False'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('OE', 'Open Ended'), ('FB', 'Fill in the Blanks'), ('SA', 'Short Answer'), ('M', 'Matching'), ('IM', 'Image Matching'), ('IA', 'Image Answering'), ('O', 'Ordering')], default='TF', max_length=2)),
                ('answer_required', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('points', models.FloatField(default=1)),
                ('display_points', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tf_correct_answer', models.BooleanField(default=True)),
                ('tf_true_first', models.BooleanField(default=True)),
                ('fb_question_title', models.CharField(blank=True, help_text='Please make sure to use the {dash} variable in your question title to show the blanks in your question. You can use multiple {dash} variables in one question.', max_length=255)),
                ('fb_correct_answer', models.CharField(blank=True, help_text='Separate multiple answers by a vertical bar |. 1 answer per {dash} variable is defined in the question. Example: Apple | Banana | Orange', max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ('quiz', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_format', models.CharField(choices=[('T', 'Only Text'), ('I', 'Only Image'), ('B', 'Text & Image both')], default='T', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('o_correct_order', models.PositiveIntegerField(default=0)),
                ('m_matched_ans_title', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_for_options', to='media_library.media')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question')),
            ],
            options={
                'ordering': ('question', 'sort_order'),
            },
        ),
    ]
