# Generated by Django 4.2.3 on 2023-08-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('C', 'Correct'), ('I', 'Incorrect'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='instructor_feedback',
            field=models.TextField(blank=True),
        ),
    ]
