# Generated by Django 4.2.3 on 2023-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_answer_status_attempt_instructor_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='seed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='feedback_mode',
            field=models.CharField(choices=[('D', 'Default'), ('R', 'Reveal Mode'), ('T', 'Retry Mode')], default='D', max_length=1),
        ),
    ]
