# Generated by Django 4.2.3 on 2023-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_attempt_seed_alter_quiz_feedback_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='o_correct_order',
        ),
        migrations.AddField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('TF', 'True/False'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('OE', 'Open Ended'), ('FB', 'Fill in the Blanks'), ('SA', 'Short Answer'), ('M', 'Matching'), ('IM', 'Image Matching'), ('IA', 'Image Answering'), ('O', 'Ordering')], default='TF', max_length=2),
        ),
    ]
