# Generated by Django 4.2.3 on 2023-08-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment'),
        ('quizzes', '0008_remove_option_o_correct_order_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.enrollment'),
            preserve_default=False,
        ),
    ]
