# Generated by Django 4.2.3 on 2023-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_attempt_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_layout',
            field=models.CharField(choices=[('S', 'Single Question'), ('B', 'Question Below Each Other')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_order',
            field=models.CharField(choices=[('R', 'Random'), ('S', 'Sorting')], default='R', max_length=1),
        ),
    ]
