# Generated by Django 4.2.3 on 2023-07-31 09:45

from django.db import migrations, models
import media_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=media_library.models.user_directory_path, validators=[media_library.models.validate_file_extension]),
        ),
    ]
