# Generated by Django 4.2.3 on 2023-07-31 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_library', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
    ]
