# Generated by Django 4.2.3 on 2023-09-14 09:27

from django.db import migrations, models
import media_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_media_options_alter_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, default='media_library/default_thumbnail.jpg', upload_to=media_library.models.user_directory_path),
        ),
    ]
